### PR TITLE
Update to work with Spree 3.1.0

### PR DESCRIPTION
**Pull request by handerson**
- add Spartan's `.rubocop.yml`
- update Spree dependency to 3.1.0
- use `Spree::PermittedAttributes` instead of `attr_accessible`
- override `Spree::OrderUpdater.update_item_total` to include add-on pricing
- make misc updates to work with Spree 3.1.0 and have tests passing

### CODE REVIEW

**Comment by bbrock25** [comment]
👍

**Comment by squaresurf** [comment]
Careful. CircleCI is failing.

**Comment by bbrock25** [comment]
@squaresurf its passing locally, we haven't set up running a bare rails project for testing only yet.

**Comment by squaresurf** [comment]
Ah ok. You guys know what's up then :smile:

**Comment by handerson** [comment]
Waiting on https://github.com/spartansystems/fanfalo-spree/pull/23 to go through before deleting the branch.

**Pull request merged**
